import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./Post.module.scss";
import { useEffect, useState } from "react";
import { Post } from "@/stores/posts/types";
import { postRequest } from "@/axios";
import Navbar from "@/components/Navbar/Navbar";
import { useAppSelector } from "@/stores/hooks";
import Link from "next/link";
import { RiPencilFill } from "react-icons/ri";
import { FaTrash } from "react-icons/fa";
import DeleteModal from "@/components/DeleteModal";

const Post = () => {
   const { user } = useAppSelector((state) => state.auth);
   const router = useRouter();
   const [notFoundMessage, setNotFoundMessage] = useState<string>("");
   const { postid } = router.query;
   const [post, setPost] = useState<Post>();
   const [modalStatus, setModalStatus] = useState<boolean>(false);

   useEffect(() => {
      if (postid) {
         (async () => {
            try {
               const { data } = await postRequest(Number(postid));
               setPost(data);
               setNotFoundMessage("");
            } catch (error) {
               console.log(error);
               setNotFoundMessage("Post not found");
            }
         })();
      }
   }, [postid]);

   const today = new Date(`${post?.created_at}`);

   return (
      <>
         <Head>
            <title>Profile</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <div className={styles.Container}>
            {post ? (
               <div>
                  <div>
                     <h2>{post.title}</h2>
                     <span>{today.toLocaleDateString("en-US")}</span>
                  </div>
                  <span>{post.subtitle}</span>
                  <p>{post.description}</p>
                  <div>
                     <Link href={`/profile/${post.user.id}`}>
                        <span>{post.user.name}</span>
                     </Link>
                     {post.user.id === user.id && (
                        <div className={styles.Buttons}>
                           <button
                              onClick={() => {
                                 setModalStatus(true);
                              }}>
                              <FaTrash />
                           </button>
                           <Link href={`/update/${post.id}`}>
                              <RiPencilFill />
                           </Link>
                        </div>
                     )}
                  </div>
               </div>
            ) : (
               <h1>{notFoundMessage}</h1>
            )}
         </div>
         <DeleteModal
            status={modalStatus}
            router={router}
            setStatus={setModalStatus}
            post={post}
         />
      </>
   );
};

export default Post;
