import { useRouter } from "next/router";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from "./Profile.module.scss";
import { useAppSelector } from "@/stores/hooks";
import { useEffect, useState } from "react";
import { Post } from "@/stores/posts/types";

const User = () => {
   const { posts } = useAppSelector((state) => state.posts);
   const [post, setPost] = useState<Post | null>();
   const [postNotFoundMessage, setPostNotFoundMessage] = useState<string>();
   const router = useRouter();
   const { userid } = router.query;

   useEffect(() => {
      if (!isNaN(Number(userid))) {
         const findedPost = posts.find((post: Post) => post.user.id === Number(userid));

         if (findedPost) {
            setPost(findedPost);
            setPostNotFoundMessage("");
         } else {
            setPost(null);
            setPostNotFoundMessage("User not found");
         }
      } else {
         setPostNotFoundMessage("Invalid post id");
      }
   }, [posts, userid]);

   const today = new Date(`${post?.created_at}`);

   return (
      <>
         <Head>
            <title>Profile {post && `- ${post.user.name.toLocaleUpperCase()}`}</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <div className={styles.Container}>
            {post ? (
               <div>
                  <div>
                     ID: <span>{post.user.id}</span>
                  </div>
                  <div>
                     NAME: <span>{post.user.name}</span>
                  </div>
                  <div>
                     EMAIL: <span>{post.user.email}</span>
                  </div>
                  <div>
                     JOINED: <span>{today.toLocaleDateString("en-US")}</span>
                  </div>
               </div>
            ) : (
               <h1>{postNotFoundMessage}</h1>
            )}
         </div>
      </>
   );
};

export default User;
