import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from "./Profile.module.scss";
import { useAppDispatch, useAppSelector } from "@/stores/hooks";
import { login } from "@/stores/auth/authSlice";
import { useRouter } from "next/router";

const Profile = () => {
   const { user } = useAppSelector((state) => state.auth);
   const dispatch = useAppDispatch();
   const router = useRouter();
   const today = new Date(user.created_at);

   const logoutHandle = () => {
      localStorage.removeItem("token");
      dispatch(
         login({
            status: false,
            id: 0,
            name: "",
            email: "",
            token: "",
            created_at: "",
         })
      );
      router.push("/login");
   };

   return (
      <>
         <Head>
            <title>Profile</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <div className={styles.Container}>
            <div>
               <div>
                  ID: <span>{user.id}</span>
               </div>
               <div>
                  NAME: <span>{user.name}</span>
               </div>
               <div>
                  EMAIL: <span>{user.email}</span>
               </div>
               <div>
                  JOINED: <span>{today.toLocaleDateString("en-US")}</span>
               </div>
               <button onClick={logoutHandle}>Logout</button>
            </div>
         </div>
      </>
   );
};

export default Profile;
