import Head from "next/head";
import styles from "./NotFound.module.scss";
import Link from "next/link";

export default function NotFound() {
   return (
      <>
         <Head>
            <title>404</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <div className={styles.Container}>
            <h1>404</h1>
            <p>
               No such page found return to <Link href='/'>home page</Link>
            </p>
         </div>
      </>
   );
}
