import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from "./Create.module.scss";
import { useRouter } from "next/router";
import { toast } from "react-hot-toast";
import { createPostRequest } from "@/axios";

const Create = () => {
   const router = useRouter();

   const submitHandle = async (e: any) => {
      e.preventDefault();

      const { title, subtitle, description } = e.target;

      if (title.value.length < 10 || title.value.length > 40) {
         toast.error("Title must be between 6 and 40 values");
         return;
      }
      if (subtitle.value.length < 15 || subtitle.value.length > 80) {
         toast.error("Subtitle ust be between 15 and 80 values");
         return;
      }
      if (description.value.length < 100 || description.value.length > 700) {
         toast.error("Description must be between 100 and 700 values");
         return;
      }

      try {
         await createPostRequest({
            title: title.value,
            subtitle: subtitle.value,
            description: description.value,
         });
         setTimeout(() => {
            router.push("/");
         }, 0);
      } catch (error) {
         console.log(error);
      }
   };

   return (
      <>
         <Head>
            <title>Create Post</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <div className={styles.Container}>
            <div className={styles.CreateInner}>
               <form onSubmit={submitHandle} className={styles.Form}>
                  <input name='title' placeholder='Title' type='text' />
                  <input name='subtitle' placeholder='Subtitle' type='text' />
                  <textarea name='description' placeholder='Description'></textarea>
                  <button>Create</button>
               </form>
            </div>
         </div>
      </>
   );
};

export default Create;
