import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import styles from "./Search.module.scss";
import { useRouter } from "next/router";
import { toast } from "react-hot-toast";
import { createPostRequest } from "@/axios";

const Search = () => {
//    const router = useRouter();

//    const submitHandle = async (e: any) => {
//       e.preventDefault();

//       const { title, subtitle, description } = e.target;

//       try {
//          await createPostRequest({
//             title: title.value,
//             subtitle: subtitle.value,
//             description: description.value,
//          });
//          setTimeout(() => {
//             router.push("/");
//          }, 0);
//       } catch (error) {
//          console.log(error);
//       }
//    };

   return (
      <>
         <Head>
            <title>Table</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <table className={styles.Container}>
            <td className={styles.table}></td>
            <tr></tr>
         </table>
      </>
   );
};

export default Search;
